### ISSUE TITLE
Translate DCRC06 to Portuguese

### ISSUE THREAD

**Issue by pLabarta** [pLabarta/dcrwebcomic#24]

**Comment by edssneto** [comment]
[Translate DCRC06 to Portuguese.txt](https://github.com/pLabarta/dcrwebcomic/files/4140834/Translate.DCRC06.to.Portuguese.txt)

**Comment by Reidiojed** [comment]
Already uploaded a version at /dcrwebcomic/tree/master/06%20-%20The%20Fork%20Menace/Images/pr

If everything's ok, I'll upload the square version too.

I highly recommend **bolding** some words as the english version does.
